version: "3"

services:
  main_build:
    build: .
    volumes:
      - ./:/Nemo-S
    working_dir: /Nemo-S
    command: make build
  config_build:
    build: .
    volumes:
      - ./:/Nemo-S
    working_dir: /Nemo-S
    command: make config

