version: "3"

services:
  main_build:
    build: .
    volumes:
      - ./:/Nemo
    working_dir: /Nemo
    command: make build
  config_build:
    build: .
    volumes:
      - ./:/Nemo
    working_dir: /Nemo
    command: make config

